# Github action to regenerate the site embeddings every evening at midnight
name: Embed URLs

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
    build_emebeddings:
        runs-on: ubuntu-latest

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Runhouse with AWS dependencies
        run: |
            python -m pip install --upgrade pip
            pip install runhouse[aws] hamilton

      # Optional: You can use Runhouse CLI to set up your AWS credentials
      # - name: Configure AWS credentials via Runhouse login
      #   run: runhouse login -y ${{ secrets.RH_TOKEN }}

      - name: Run the embedding script and save the embedding revision
        run: python batch_process.py

